platform :ios, '9.0'
#use_frameworks!个别需要用到它，比如reactiveCocoa
xcodeproj ‘Test.xcodeproj' 
target 'Test' do
pod 'MBProgressHUD', '~> 0.9.2'
pod 'SDWebImage', '~>3.8'
pod 'AFNetworking', '~> 3.0'
pod 'SSKeychain'
pod 'Masonry'
pod 'MJRefresh'
pod 'MJExtension'
pod 'SDCycleScrollView','~> 1.64'
pod 'SKTagView'
end


